### ISSUE TITLE
Crash in mfs_print from utf-8 decode?

### ISSUE THREAD

**Issue by verygreen** [platomav/MEAnalyzer#18] opened 2020-02-13 06:32 UTC
```
╔══════════════════════════════════════╗
║          MFS Volume Header           ║
╟────────────────────────┬─────────────╢
║       Signature        │   724F6201  ║
╟────────────────────────┼─────────────╢
║       Unknown 0        │     0x01    ║
╟────────────────────────┼─────────────╢
║       Unknown 1        │   0x000000  ║
╟────────────────────────┼─────────────╢
║      Volume Size       │   0xD6C80   ║
╟────────────────────────┼─────────────╢
║   File Record Count    │     1024    ║
╚════════════════════════╧═════════════╝

    MFS System Volume Size is VALID

    Analyzing MFS Low Level File 2 (Anti-Replay) ...

    Analyzing MFS Low Level File 3 (Anti-Replay) ...

    Analyzing MFS Low Level File 5 (Quota Storage) ...

    Analyzing MFS Low Level File 7 (OEM Configuration) ...

Error: ME Analyzer crashed, please report the following:

Traceback (most recent call last):
  File "MEA.py", line 10160, in <module>
    cse_unpack(variant, fpt_part_all, bpdt_part_all, file_end, fpt_start if rgn_exist else -1, fpt_chk_fail, cse_lt_chk_fail)
  File "MEA.py", line 4694, in cse_unpack
    mfs_parsed_idx,intel_cfg_hash_mfs,mfs_info,pch_init_final,vol_ftbl_id,config_rec_size = mfs_anl(os.path.join(mod_f_path[:-4], ''), part_start, part_end, variant) # Parse MFS
  File "MEA.py", line 6572, in mfs_anl
    pch_init_info = mfs_cfg_anl(mfs_file[0], mfs_file[1], rec_folder, root_folder, config_rec_size, pch_init_info, vol_ftbl_id) # Parse MFS Config Records
  File "MEA.py", line 6812, in mfs_cfg_anl
    rec_hdr_pt = rec_hdr.mfs_print() # MFS Configuration Record PrettyTable Object
  File "MEA.py", line 1128, in mfs_print
    pt.add_row(['Name', self.FileName.decode('utf-8')])
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 0: invalid start byte
```

This image comes directly from the flash chip of the system, I also have a pristine image that's supposed to be there and they don't match, one can see that some sections on the actual chip are relocated or omitted (the pristine image can be processed by MEAnalyzer just fine).

When looking at produced results, the entry for AFSP is not really there in the pristine image, though I am not sure if it matters or not.

Images are available if that's helpful.

```
[green@fatbox2 MEAnalyzer]$ ls Unpacked_elk-19.36.2.1.bin
'BPDT [4].bin'              'PDRP 0000 [0x001000]'
'BPDT [4].txt'              'PDRP 0000 [0x001000].txt'
'FTPR 0000 [0x120000]'      'PMCP 0001 [0x110000]'
'FTPR 0000 [0x120000].bin'  'PMCP 0001 [0x110000].bin'
'FTPR 0000 [0x120000].txt'  'PMCP 0001 [0x110000].txt'
'IBBP 0000 [0x18C000]'      'RBEP 0000 [0x105000]'
'IBBP 0000 [0x18C000].bin'  'RBEP 0000 [0x105000].bin'
'IBBP 0000 [0x18C000].txt'  'RBEP 0000 [0x105000].txt'
'ISHC 0001 [0x1CD000]'      'S-BPDT 0000 [0x800200].bin'
'ISHC 0001 [0x1CD000].bin'  'S-BPDT 0001 [0x1CC000].bin'
'ISHC 0001 [0x1CD000].txt'  'SMIP 0000 [0x101000]'
'IUNP 0001 [0x310000]'      'SMIP 0000 [0x101000].bin'
'IUNP 0001 [0x310000].bin'  'SMIP 0000 [0x101000].txt'
'IUNP 0001 [0x310000].txt'  'UCOD 0000 [0x183000]'
'NFTP 0000 [0x20D000]'      'UCOD 0000 [0x183000].bin'
'NFTP 0000 [0x20D000].bin'  'UCOD 0000 [0x183000].txt'
'NFTP 0000 [0x20D000].txt'  'UEP 0000 [0x100210].bin'
'OBBP 0000 [0x801000]'      'UEPB 0000 [0x100200].bin'
'OBBP 0000 [0x801000].bin'  'UTOK 0000 [0x1CA000].bin'
'OBBP 0000 [0x801000].txt'
[green@fatbox2 MEAnalyzer]$ ls Unpacked_rom2.bin/
'AFSP 0000 [0xF0A000]'      'FPT [0xF00000].bin'
'AFSP 0000 [0xF0A000].bin'  'FPT [0xF00000].txt'
[green@fatbox2 MEAnalyzer]$ ls Unpacked_rom2.bin/AFSP\ 0000\ \[0xF0A000\]
'002 Anti-Replay'  '003 Anti-Replay'  '005 Quota Storage'
```

**Comment by platomav** [comment] 2020-02-13 09:30
Thank you for the report. Can you please send me the images so that I can check what the issue is?

**Comment by verygreen** [comment] 2020-02-13 13:28
how to send you the image? is there an email I can dump some links to or a dropbox of some sort?

**Comment by platomav** [comment] 2020-02-13 14:03
Sure, send them to winraidforum@gmail.com

**Comment by platomav** [comment] 2020-02-13 23:04
Alright, I checked and it seems that the image you are loading is corrupt at various places (MFS, SMIP etc), causing MEA to crash. The non dumped/initialized image can be analyzed and unpacked properly though. Since this is not a MEA issue but the result of firmware corruption, I'll go ahead and close this issue.

**Closed by platomav** 2020-02-13 23:04 UTC

**Comment by verygreen** [comment] 2020-02-14 00:12
hm, strange. I am pretty sure the read is good (very repeatable, there's also a bit chunk of gzipped data that decompresses without any errors).
It looks like the section not present in uninitialized image is the one with the problem to me, but if you think it's a corrupted image, I guess my only option is to try to procure a similar one from another unit and compare.

Thanks for looking into it.

**Comment by platomav** [comment] 2020-02-14 09:16
The read is good. The firmware itself is corrupt for some reason at the File System (AFSP) and at least another partition (SMIP). It's normal for the File System to not be present at the initial image before the first boot.

**Comment by verygreen** [comment] 2020-02-14 23:14
I guess if you think it's ok to crash on firmwares dumped from real flash chips as long as it works on virgin versions - then it's all fine.
(and I got another image and it's corrupted in different ways so it does not seem to be an isolated incident).

thanks.

**Comment by platomav** [comment] 2020-02-15 01:18
MEA has full support for dumped/initialized CSE firmware, which includes parsing & unpacking the File System (MFS, AFS) without problems. It's unfortunately common for the File System to corrupt itself during CSE operation which usually causes abnormal system behavior, errors at MEInfo/TXEInfo etc. When that happens, depending on the corruption, any parsing tools (MEA, FIT) may end up crashing because they encounter unexpected data. For example, if a unicode string is expected somewhere but the section is mistakenly filled with 0xFF or similar (your case), the parser will probably crash. Your dumped image has corruption at file 7 of the File System (OEM Configuration) and SMIP Partition (semi-duplicate $CPD structure). What I'm trying to say is that MEA works but the problem is at the images that you've loaded. I have tested at various dumped/initialized CSTXE 3 images without issues.
